language: R
cache: packages
r_packages:
  - devtools
  - covr
  - roxygen2
bioc_packages:
  - org.Hs.eg.db
  - reactome.db
  - BiocCheck
  - BiocStyle
before_install:
  Rscript -e 'update.packages(ask = FALSE)'
sudo: false
after_success:
  - Rscript -e 'library(covr); codecov()'
#  - R CMD BiocCheck .
os:
  - linux
r:
 - bioc-devel
notifications:
  email:
    on_success: change
    on_failure: change
