language: R
sudo: false
cache: packages

r_github_packages:
- jimhester/lintr

after_script:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'library(covr); codecov()'
#  - R CMD BiocCheck .
os:
  - linux
r:
 - bioc-devel
notifications:
  email:
    on_success: change
    on_failure: change
